name: chatteree_mobile
description: A social chat app.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/icon/interfaces/
    - assets/icons/icon/arrow/
    - assets/images/

  fonts:
    - family: GeneralSans
      fonts:
          - asset: assets/fonts/GeneralSans-Light.otf
            weight: 300
          - asset: assets/fonts/GeneralSans-Regular.otf
            weight: 400
          - asset: assets/fonts/GeneralSans-Medium.otf
            weight: 500
          - asset: assets/fonts/GeneralSans-Bold.otf
            weight: 600
          